# Generated by Django 3.0.5 on 2020-05-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_animal_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='sex',
            new_name='gender',
        ),
    ]
