# Generated by Django 3.0.5 on 2020-05-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_medicalvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalvisit',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo.Animal'),
            preserve_default=False,
        ),
    ]
