# Generated by Django 3.0.5 on 2020-05-31 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoo', '0009_medicalvisit_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalVisit',
            new_name='MedicalReport',
        ),
    ]
