# Generated by Django 3.2.3 on 2021-06-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0018_animal_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='fav',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals', models.ManyToManyField(to='zoo.Animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.userprofileinfo')),
            ],
        ),
    ]
